### ISSUE TITLE
[BUG] The __main__.validate_task_name fails for all task names

### ISSUE THREAD

**Issue by AlexisMignon** [alliander-opensource/openstf#145]
**Describe the bug**
Using Python 3.8 on a Linux platform, the function `__main__.validate_task_name(name)` fails with an exception due to the attempt to use `startswith` on a `PosixPath` object.

**To Reproduce**

```python
from openstf.__main__ import validate_task_name
validate_task_name("test")
```
Leading to the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/pkgutil.py", line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/tasks')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-22c7954f6bdb>", line 1, in <module>
    validate_task_name("test")
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/__main__.py", line 29, in validate_task_name
    task_modules = [m for _, m, _ in pkgutil.iter_modules([task_pkg_dir])]
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/__main__.py", line 29, in <listcomp>
    task_modules = [m for _, m, _ in pkgutil.iter_modules([task_pkg_dir])]
  File "/usr/lib/python3.8/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1469, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
validate_task_name("test")
Traceback (most recent call last):
  File "/usr/lib/python3.8/pkgutil.py", line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/tasks')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-22c7954f6bdb>", line 1, in <module>
    validate_task_name("test")
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/__main__.py", line 29, in validate_task_name
    task_modules = [m for _, m, _ in pkgutil.iter_modules([task_pkg_dir])]
  File "/home/amignon/Projets/RTE/OpenSTF/openstf/openstf/__main__.py", line 29, in <listcomp>
    task_modules = [m for _, m, _ in pkgutil.iter_modules([task_pkg_dir])]
  File "/usr/lib/python3.8/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1469, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Additional context**

The faulty instruction is here https://github.com/alliander-opensource/openstf/blob/029b868355be68411111d0801ccef8f5b5fbe8b7/openstf/__main__.py#L29 

Coming from the call to `pkgutil.iter_modules()`

The problem could be solved by replacing:

```python
    task_modules = [m for _, m, _ in pkgutil.iter_modules([task_pkg_dir])]
```
with
```python
    task_modules = [m for _, m, _ in pkgutil.iter_modules([str(task_pkg_dir)])]
```

**Comment by FrankKr** [comment]
Thanks for your report and your suggestion for a fix. I'm looking into it now.

**Comment by FrankKr** [comment]
@AlexisMignon I could not replicate the issue (not on my windows machine using PurePosixPath, or on de unix-based container used in the build-action. However, I'm happy to incorporate your proposed solution, for which I've made PR #153.
If you could confirm that it indeeds fixes your issue, I will merge the PR afterwards. 

Also, thanks for your contribution to improving openstf. Although the source code is publicly available, we are still very much in the process of making it more external-user-friendly. Your feedback or remarks are greatly appreciated! Also, if you have any questions, please don't hesitate to reach out!

**Comment by AlexisMignon** [comment]
Hello.

You're welcome. The fact that you cannot replicate the bug is interesting. What version of Python do you use ? I may have to use openstf in the future so more feedback may come.

I will test the modifications as soon as I can.

**Comment by bremme** [comment]
Hi @AlexisMignon thanks for reporting this issue. To be honest we don't really use the `__main__` interface our self at the moment, that's why we probably missed this issue. Just to be clear, instead of using the module interface: `python -m openstf task <task_name>`. You can also just run the tasks directly: `python openstf/tasks/<task_name>`. (You might have to install openstf and or add the project directory to your Python path)

Back to your issue. I have been able to reproduce the issue. You are right that the root cause of the exception is some code calling `startswith` on a `PosixPath` (perhaps the `WindowsPath` has a `startswith` method?). I'm not totally sure what introduced this bug or that it never really worked on Linux. But in any case if we just pass in the task package directory as a string to `pkgutil.iter_modules` everything should work as expected:

```python
def validate_task_name(task_name):
    task_pkg_dir = PROJECT_ROOT / "openstf" / "tasks"
    # convert to string before calling iter_modules
    task_modules = [m for _, m, _ in pkgutil.iter_modules([str(task_pkg_dir)])]

    if task_name not in task_modules:
        raise RuntimeError(
            f"Unknown task: '{task_name}', valid tasks are :{', '.join(task_modules)}."
        )
```

You are more then welcome to open an PR to solve this (small) bug. Otherwise we will try to add it to the next release.

**Comment by alexis-mignon** [comment]
This seems to come from a bug in the 3.8.10 release of Python. The release notes of 3.8.11 mention a bugfix for this issue:

https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-11-final

**Comment by bremme** [comment]
@alexis-mignon I see. Not sure if those fixes are not merged upstream, but I did get the same exception (`AttributeError: 'PosixPath' object has no attribute 'startswith'`) when using Python 3.9.5. 

By the way, @FrankKr did already open a PR to fix this issue: https://github.com/alliander-opensource/openstf/pull/153.
